package com.sevenfiguredevelopers;

import com.sevenfiguredevelopers.controller.SevenFigureDeveloperApp;

import java.util.ArrayList;
import java.util.List;

public class QuestionDB  {

    private List<Question> questionDatabase = new ArrayList<>(List.of (
            // id     difficulty     question         answer
            new Question(1, Difficulty.EASY, "What is a class? \n A: the \"blueprint\" " +
                    "when creating objects. \n B. An integer \n C. size of variable \n D. constructor  " , "A"),
            new Question(2, Difficulty.EASY, "What is the lowest amount of constructors an object can have? " +
                    "\n A: 1 \n B: 0 \n C: 2 \n D: 3", "A"),
            new Question(3, Difficulty.EASY, "Which statement is not true in java language?\n" +
                    "\n" +
                    "(a) A public member of a class can be accessed in all the packages.\n" +
                    "(b) A private member of a class cannot be accessed by the methods of the same class.\n" +
                    "(c) A private member of a class cannot be accessed from its derived class.\n" +
                    "(d) A protected member of a class can be accessed from its derived class.\n",
                    "B"),
            new Question(4, Difficulty.EASY, "To prevent any method from overriding, we declare the method as,\n" +
                    "(a) static (b) const (c) final (d) abstract ",
                    "C"),
            new Question(5, Difficulty.MEDIUM, "An object is an instance of a _____ ? \n " +
                    "A: method \n B: thing \n C: class \n D: object", "C"),
            new Question(6, Difficulty.MEDIUM, "What is the result of this expression: 2 % 2 == 1 ? " +
                    "\n A: True \n B: False", "B"),
            new Question(7, Difficulty.MEDIUM, "What is printed by the following statement?\n" +
                    "System.out.print(“Hello,\\nworld!”);\n" +
                    "\n" +
                    "(a) Hello, \\nworld! \n" +
                    "(b) Hello, world!\n" +
                    "(c)\n" +
                    "(d) “Hello, \\nworld!”",
                    "C"),
            new Question(8, Difficulty.MEDIUM, "What is byte code in the context of Java?\n" +
                    "\n" +
                    "(a) The type of code generated by a Java compiler.\n" +
                    "(b) The type of code generated by a Java Virtual Machine.\n" +
                    "(c) It is another name for a Java source file.\n" +
                    "(d) It is the code written within the instance methods of a class.",
                    "A"),
            new Question(9, Difficulty.HARD, "Which collection doesn't allow duplicates ? \n A: Set \n B: HashMap \n C: ArrayList \n D: List", "A"),
            new Question(10, Difficulty.HARD, "Mark the incorrect statement from the following:\n" +
                    "\n" +
                    "(a) Java is not a language for internet programming.\n" +
                    "(b) In java it is not easy to write C-like so called procedural programs\n" +
                    "(c) In java language objects have to be manipulated\n" +
                    "(d) In java language error processing is built into the language", "D"),
             new Question(11, Difficulty.EASY, "Which is the characteristic of an immutable class? \n A: Objects of the class cannot change content after creation \n" +
                     " B: Objects of the class cannot be parsed \n C: The class has all static methods \n D: The class has all static final fields", "A"),
            new Question(12, Difficulty.EASY, "Which of the following is not an interface?  \n A: Map \n" +
                    " B: SortedMap \n C: ArrayList \n D: Collection", "C"),
            new Question(13, Difficulty.MEDIUM, "What was the original name of Java? \n A: WebC \n" +
            " B: Oak \n C: C- \n D: SunLang", "B"),
            new Question(14, Difficulty.MEDIUM, "What is the output of: System.out.println(1+2+” = “+1+2); ?  \n A: 12=3 \n" +
            " B: 3=3 \n C: 12=12 \n D: 3=12", "D"),
        new Question(15, Difficulty.HARD, "Who invented Java on accident? \n A: Alan Turing \n" +
            " B: Dennis Ritchie \n C: James Gosling \n D: Bjarne Stroustroup", "C")
    ));

    public List<Question> getQuestionDatabase() {
        return questionDatabase;
    }
}